#for your build environment.
image: qdata/qciagent:master-php7.1

pipelines:
    branches: #The branch section is a container for all branch-specific pipelines
        stage:
            - step:
                script:
                    - export HOST="ftp.ord1-1.websitesettings.com"
                    - export TARGETFOLDER="/web/content/"
                    - export SOURCEFOLDER='.'
                    - export FTPUSER=$FTPUSER
                    - export FTPPSWD=$FTPPASS
                    #- composer install
                    #- php artisan october:up
                    - echo $FTPUSER
                    - echo $FTPPSWD
                    - /bin/bash /deploy.bash
                    - echo "In Stage Branch"
